import {useState} from 'react';
import {request} from '../../api/client.js';
import {useApi} from '../../hooks/useApi.js';
import Pagination from '../Pagination.jsx';
import State from '../State.jsx';
const labelFor=key=>key.replace(/([A-Z])/g,' $1').replace(/^./,c=>c.toUpperCase());
export default function ResourceEditor({resource,config}){
 const [page,setPage]=useState(1),[search,setSearch]=useState(''),[query,setQuery]=useState(''),[editing,setEditing]=useState(null),[values,setValues]=useState({}),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const r=useApi(`/${resource}/manage?${new URLSearchParams({page,search:query,limit:15})}`),cats=useApi('/categories/manage?limit=100'),subs=useApi('/subcategories/manage?limit=100'),media=useApi('/media?limit=100');
 function open(item){setError('');setEditing(item||{});setValues(Object.fromEntries(config.fields.map(([key,type])=>[key,type==='list'?(item?.[key]||[]).join('\n'):type==='checkbox'?Boolean(item?.[key]):item?.[key]??''])));}
 async function save(e){e.preventDefault();setBusy(true);setError('');const body={};for(const [key,type] of config.fields){const val=values[key];if(type==='checkbox')body[key]=Boolean(val);else if(type==='list')body[key]=String(val||'').split('\n').map(s=>s.trim()).filter(Boolean);else if(type==='number'){if(val!=='')body[key]=Number(val);}else if(val!=='')body[key]=val;else if(['subCategory','cover','portrait'].includes(key)&&editing._id)body[key]=null;else if(editing._id&&['location','email','summary','duration','icon'].includes(key))body[key]='';}
 try{await request(`/${resource}${editing._id?'/'+editing._id:''}`,{method:editing._id?'PATCH':'POST',body});setEditing(null);r.reload();}catch(err){setError(err.details?JSON.stringify(err.details):err.message);}finally{setBusy(false);}}
 async function remove(item){if(!window.confirm(`Delete ${item.name}? This cannot be undone.`))return;setError('');try{await request(`/${resource}/${item._id}`,{method:'DELETE'});r.reload();}catch(err){setError(err.message);}}
 return <section><div className="section-heading"><h1>{config.title}</h1><button onClick={()=>open()}>Add new</button></div><form className="filters" onSubmit={e=>{e.preventDefault();setQuery(search);setPage(1);}}><input aria-label="Search records" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search records"/><button>Search</button></form>{error&&<p className="error" role="alert">{error}</p>}<State loading={r.loading} error={r.error} empty={r.data?.data.length===0}/>{editing!==null&&<div className="editor-panel"><h2>{editing._id?'Edit record':'New record'}</h2><form className="editor-grid" onSubmit={save}>{config.fields.map(([key,type,required,options])=>{const value=values[key],set=value=>setValues(v=>({...v,[key]:value}));let choices=type==='category'?cats.data?.data:type==='subcategory'?subs.data?.data.filter(s=>s.category===values.category):type==='media'?media.data?.data:null;return <label key={key} className={['textarea','list'].includes(type)?'wide':''}>{labelFor(key)}{type==='checkbox'?<input type="checkbox" checked={value} onChange={e=>set(e.target.checked)}/>:['select','category','subcategory','media'].includes(type)?<select required={required} value={value} onChange={e=>{set(e.target.value);if(key==='category')setValues(v=>({...v,category:e.target.value,subCategory:''}));}}><option value="">Select…</option>{options?.map(o=><option key={o}>{o}</option>)}{choices?.map(o=><option key={o._id} value={o._id}>{o.name||o.originalName||o.filename}</option>)}</select>:['textarea','list'].includes(type)?<textarea required={required} rows={type==='textarea'?5:3} value={value} onChange={e=>set(e.target.value)} placeholder={type==='list'?'One entry per line (gallery: media IDs)':''}/>:<input required={required} type={type} value={value} onChange={e=>set(e.target.value)} min={type==='number'?0:undefined}/>}</label>;})}<div className="wide actions"><button disabled={busy}>{busy?'Saving…':'Save record'}</button><button type="button" className="secondary" onClick={()=>setEditing(null)}>Cancel</button></div></form></div>}<div className="table-wrap"><table><thead><tr><th>Name</th><th>Status</th><th>Updated</th><th>Actions</th></tr></thead><tbody>{r.data?.data.map(item=><tr key={item._id}><td>{item.name}</td><td><span className={'badge '+(item.published?'published':'')}>{item.published?'Published':'Draft'}</span></td><td>{new Date(item.updatedAt).toLocaleDateString()}</td><td className="actions"><button className="secondary" onClick={()=>open(item)}>Edit</button><button className="danger" onClick={()=>remove(item)}>Delete</button></td></tr>)}</tbody></table></div><Pagination meta={r.data?.pagination} onPage={setPage}/></section>;
}
