import {Router} from 'express';
import multer from 'multer';
import {z} from 'zod';
import {Media} from './media.model.js';
import {upload,remove,uploadDir} from './media.service.js';
import {authenticate,authorize} from '../../middleware/auth.js';
import {asyncHandler as wrap} from '../../utils/asyncHandler.js';
import {pagination} from '../../utils/query.js';
import {validId} from '../shared/resource.routes.js';
import {audit} from '../audit/audit.service.js';
import {AppError} from '../../utils/AppError.js';
const router=Router(),multipart=multer({storage:multer.memoryStorage(),limits:{fileSize:5*1024*1024,files:1,fields:1}});
router.get('/:id/file',validId,wrap(async(req,res)=>{const media=await Media.findById(req.params.id);if(!media) throw new AppError(404,'Image not found');res.set('Cache-Control','public, max-age=86400');res.type('webp').sendFile(media.filename,{root:uploadDir},err=>{if(err)res.status(err.statusCode||404).end();});}));
router.use(authenticate,authorize('admin','superadmin'));
router.get('/',wrap(async(req,res)=>{const {page,limit,skip}=pagination(req.query);const [data,total]=await Promise.all([Media.find().sort('-createdAt').skip(skip).limit(limit),Media.countDocuments()]);res.json({success:true,data,pagination:{page,limit,total,pages:Math.ceil(total/limit)}});}));
router.post('/',multipart.single('file'),wrap(async(req,res)=>{const alt=z.string().max(300).parse(req.body.alt||'');const data=await upload(req.file,alt,req.admin._id);await audit(req,'upload','Media',data._id);res.status(201).json({success:true,data});}));
router.patch('/:id',validId,wrap(async(req,res)=>{const data=z.object({alt:z.string().max(300)}).strict().parse(req.body);const media=await Media.findByIdAndUpdate(req.params.id,data,{new:true,runValidators:true});if(!media)throw new AppError(404,'Image not found');res.json({success:true,data:media});}));
router.delete('/:id',validId,wrap(async(req,res)=>{await remove(req.params.id);await audit(req,'delete','Media',req.params.id);res.status(204).end();}));
export default router;
