import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import cookieParser from 'cookie-parser';
import pinoHttp from 'pino-http';
import {randomUUID} from 'node:crypto';
import mongoose from 'mongoose';
import {env} from './config/env.js';
import {logger} from './config/logger.js';
import {globalLimit} from './middleware/rateLimits.js';
import {trustedOrigin} from './middleware/auth.js';
import {errorHandler} from './middleware/errorHandler.js';
import {AppError} from './utils/AppError.js';
import categoriesRoutes from './modules/categories/categories.routes.js';
import subcategoriesRoutes from './modules/subcategories/subcategories.routes.js';
import productsRoutes from './modules/products/products.routes.js';
import teammembersRoutes from './modules/team-members/team-members.routes.js';
import servicesRoutes from './modules/services/services.routes.js';
import testimonialsRoutes from './modules/testimonials/testimonials.routes.js';
import authRoutes from './modules/auth/auth.routes.js';
import adminRoutes from './modules/admin/admin.routes.js';
import websiteinfoRoutes from './modules/website-info/website-info.routes.js';
import mediaRoutes from './modules/media/media.routes.js';
import inquiriesRoutes from './modules/inquiries/inquiries.routes.js';
import auditRoutes from './modules/audit/audit.routes.js';
import dashboardRoutes from './modules/dashboard/dashboard.routes.js';
export const app=express();
app.disable('x-powered-by');
app.use(helmet(),cors({origin:env.CLIENT_ORIGIN,credentials:true}),pinoHttp({logger,genReqId:()=>randomUUID()}),cookieParser());
app.use(express.json({limit:'256kb'}));
app.get('/health',(req,res)=>res.status(mongoose.connection.readyState===1?200:503).json({status:mongoose.connection.readyState===1?'ready':'unavailable'}));
app.use('/api',globalLimit,trustedOrigin);
app.use('/api/v1/categories',categoriesRoutes);
app.use('/api/v1/subcategories',subcategoriesRoutes);
app.use('/api/v1/products',productsRoutes);
app.use('/api/v1/team-members',teammembersRoutes);
app.use('/api/v1/services',servicesRoutes);
app.use('/api/v1/testimonials',testimonialsRoutes);
app.use('/api/v1/auth',authRoutes);
app.use('/api/v1/admin',adminRoutes);
app.use('/api/v1/website-info',websiteinfoRoutes);
app.use('/api/v1/media',mediaRoutes);
app.use('/api/v1/inquiries',inquiriesRoutes);
app.use('/api/v1/audit',auditRoutes);
app.use('/api/v1/dashboard',dashboardRoutes);
app.use((req,res,next)=>next(new AppError(404,'Endpoint not found')));
app.use(errorHandler);
