import test,{before,after} from 'node:test';
import assert from 'node:assert/strict';
import mongoose from 'mongoose';
import bcrypt from 'bcryptjs';
import supertest from 'supertest';
import sharp from 'sharp';
import 'dotenv/config';
process.env.NODE_ENV='test';process.env.JWT_SECRET='test-secret-at-least-32-characters-long';
const uri=process.env.TEST_MONGODB_URI;
if(!uri||!new URL(uri.replace('mongodb://','http://')).pathname.endsWith('_test'))throw new Error('TEST_MONGODB_URI must point to a disposable database ending in _test');
process.env.MONGODB_URI=uri;process.env.CLIENT_ORIGIN='http://localhost:5173';
const {app}=await import('../../src/app.js');
const {Admin}=await import('../../src/modules/admin/admin.model.js');
const {Category}=await import('../../src/modules/categories/categories.model.js');
const {SubCategory}=await import('../../src/modules/subcategories/subcategories.model.js');
const {Product}=await import('../../src/modules/products/products.model.js');
const {Media}=await import('../../src/modules/media/media.model.js');
const {remove}=await import('../../src/modules/media/media.service.js');
const api=supertest(app),agent=supertest.agent(app),origin='http://localhost:5173';let cat,sub;
before(async()=>{await mongoose.connect(uri);await mongoose.connection.dropDatabase();await Admin.create({name:'Test Admin',email:'admin@test.local',passwordHash:await bcrypt.hash('TestPassword123!',12),role:'superadmin'});cat=await Category.create({name:'Residential',slug:'residential',description:'Residential design',published:true});sub=await SubCategory.create({name:'Homes',slug:'homes',description:'Private homes',category:cat._id,published:true});await Product.create({name:'Draft',slug:'draft',description:'Private draft',category:cat._id,type:'design',published:false});});
after(async()=>{for(const m of await Media.find())await remove(m._id);await mongoose.connection.dropDatabase();await mongoose.disconnect();});
test('public reads hide draft content',async()=>{const r=await api.get('/api/v1/products');assert.equal(r.status,200);assert.equal(r.body.data.length,0);});
test('writes require trusted origin and admin session',async()=>{assert.equal((await api.post('/api/v1/categories').send({})).status,403);assert.equal((await api.post('/api/v1/categories').set('Origin',origin).send({})).status,401);});
test('login, validated CRUD, relations, uploads and revocation',async()=>{
 assert.equal((await agent.post('/api/v1/auth/login').set('Origin',origin).send({email:'admin@test.local',password:'TestPassword123!'})).status,200);
 const r=await agent.post('/api/v1/products').set('Origin',origin).send({name:'Published',description:'Published project',category:String(cat._id),subCategory:String(sub._id),type:'design',published:true});assert.equal(r.status,201);const id=r.body.data._id;
 assert.equal((await agent.patch('/api/v1/products/'+id).set('Origin',origin).send({price:-5})).status,422);
 assert.equal((await agent.delete('/api/v1/categories/'+cat._id).set('Origin',origin)).status,409);
 assert.equal((await agent.get('/api/v1/products/manage')).body.pagination.total,2);
 assert.equal((await api.get('/api/v1/products')).body.data.length,1);
 const buffer=await sharp({create:{width:20,height:20,channels:3,background:'#ffffff'}}).png().toBuffer();
 const upload=await agent.post('/api/v1/media').set('Origin',origin).attach('file',buffer,{filename:'test.png',contentType:'image/png'}).field('alt','Test image');assert.equal(upload.status,201);
 assert.equal((await api.get('/api/v1/media/'+upload.body.data._id+'/file')).status,200);
 assert.equal((await agent.delete('/api/v1/media/'+upload.body.data._id).set('Origin',origin)).status,204);
 assert.equal((await agent.delete('/api/v1/products/'+id).set('Origin',origin)).status,204);
 assert.equal((await agent.post('/api/v1/auth/logout').set('Origin',origin)).status,204);
 assert.equal((await agent.get('/api/v1/auth/me')).status,401);
});
test('inquiries validate and keep personal data private',async()=>{assert.equal((await api.get('/api/v1/inquiries')).status,401);assert.equal((await api.post('/api/v1/inquiries').set('Origin',origin).send({name:'Visitor',email:'visitor@example.com',message:'Please help us design a new family residence.'})).status,201);});
